# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: read

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: bun build and test
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup node
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Clean install dependencies and build
        run: |
          bun i
          bun run build

      # Runs a set of commands using the runners shell
      - name: Run test
        run: |
          bun run test-all
